#The first line is used for comment
!setname 0x7042 Nordic Horror
!setname 0x3fc Soul of the Evil
!setname 0x406 Shadow Torment
!setname 0x3e8 Ultimate God
!setname 0x3f2 Progenitor Gods
!setname 0x4B0 Cult
#The first line is used for comment
!counter 0x14B0 Sun Counter
