#The first line is used for comment
!setname 0x7042 Nordic Horror
!setname 0x3e8 Archangel
!setname 0x3f2 Jashin
!setname 0x3FC Orichalcos
!setname 0x406 Tarot
!setname 0x410
!setname 0x41A
!setname 0x424
!setname 0x4B0 Chosen Pharaoh
#The first line is used for comment
!counter 0x14B0 Sun Counter
